name: Terraform Apply

on:
  workflow_dispatch:  # 👈 hanya bisa dijalankan manual dari UI GitHub

jobs:
  terraform:
    name: Terraform Manual Apply
    runs-on: ubuntu-latest

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      TF_VAR_google_credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      TF_VAR_project_id: "sodium-pattern-465207-m9"
      TF_VAR_region: "us-central1"
      TF_VAR_zone: "us-central1-a"

    defaults:
      run:
        working-directory: 8. CI-CD Terraform/

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan.out -lock=false

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan.out
