name: Terraform Destroy (Multi Folder) 

on:
  workflow_dispatch:
    inputs: # Pilih folder yang ingin di-destroy
      target_folder:
        description: "Folder Terraform yang ingin di-destroy"
        required: true
        default: "Choose a folder"
        type: choice
        options:
          - 8. CI-CD Terraform
          - 9. GCS Terraform

jobs:
  destroy:
    name: Terraform Manual Destroy
    runs-on: ubuntu-latest

    env: 
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS_GCS }}          # 🔄 GCS backend credentials
      TF_VAR_google_credentials_json: ${{ secrets.GCP_CREDENTIALS }}  # 🔄 Provider credentials
      TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}                 # ✅ Project ID
      TF_VAR_region: ${{ secrets.GCP_REGION }}                         # ✅ Region
      TF_VAR_zone: ${{ secrets.GCP_ZONE }}                             # ✅ Zone

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0 

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ github.event.inputs.target_folder }}

      - name: 💣 Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ${{ github.event.inputs.target_folder }}
