name: Terraform Apply (Multi Folder)

on:
  workflow_dispatch:
    inputs: # Pilih folder Terraform dari GitHub UI
      target_folder:
        description: "Folder Terraform yang ingin dijalankan"
        required: true
        default: "Choose a folder"
        type: choice
        options:
          # - 8. CI-CD Terraform
          # - 9. Cloud Run from Source Repo
          - 10. Cloud Run with Build



jobs:
  terraform:
    name: Terraform Manual Apply
    runs-on: ubuntu-latest

# ======== start untuk step  8-9 ======== 
    # env: 
    #   GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS_GCS }}          # 🔄 GCS,coud-run credentials
    #   TF_VAR_google_credentials_json: ${{ secrets.GCP_CREDENTIALS_GCS }}  # 🔄 Provider credentials
    #   TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}                 # ✅ Project ID
    #   TF_VAR_region: ${{ secrets.GCP_REGION }}                         # ✅ Region
    #   TF_VAR_zone: ${{ secrets.GCP_ZONE }}                             # ✅ Zone
    #   TF_VAR_image_url: "gcr.io/cloudrun/hello"
    #   TF_VAR_service_name: "flask-cloudrun-testing"
# ========  end untuk step  8-9 ======== 

# ======== start untuk step  10 ======== 
    env: 
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS_GCS }}          # 🔄 GCS,coud-run credentials
      TF_VAR_google_credentials_json: ${{ secrets.GCP_CREDENTIALS_GCS }}  # 🔄 Provider credentials
      TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}                 # ✅ Project ID
      TF_VAR_region: ${{ secrets.GCP_REGION }}                         # ✅ Region
      TF_VAR_zone: ${{ secrets.GCP_ZONE }}                             # ✅ Zone

      TF_VAR_repo_name: "cloudrun-testing-with-terraform"        # ✅ Artifact Registry repository name
      TF_VAR_image_name: "cloudrun-testing"
      TF_VAR_service_name: "cloudrun-testing"
      TF_VAR_github_owner: "hamdahamda"
      TF_VAR_github_repo: "latihan-css-web"

# ========  end untuk step  10 ======== 


    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0 

      - name: 🧪 Terraform Init
        run: terraform init
        working-directory: ${{ github.event.inputs.target_folder }} 

      - name: ✅ Terraform Validate
        run: terraform validate -no-color
        working-directory: ${{ github.event.inputs.target_folder }}

      - name: 📦 Terraform Plan
        run: terraform plan -out=tfplan.out -lock=false
        working-directory: ${{ github.event.inputs.target_folder }} 

      - name: 🚀 Terraform Apply
        run: terraform apply -auto-approve tfplan.out
        working-directory: ${{ github.event.inputs.target_folder }} 
