name: Terraform Destroy (Multi Folder) # 🔄 UPDATE

on:
  workflow_dispatch:
    inputs: # 🆕 NEW: Pilih folder yang ingin di-destroy
      target_folder:
        description: "Folder Terraform yang ingin di-destroy"
        required: true
        default: "Choose a folder"
        type: choice
        options:
          - 8. CI-CD Terraform
          - 9. GCS Terraform

jobs:
  destroy:
    runs-on: ubuntu-latest

    env: # 🔄 Tetap sama, pastikan project & credentials benar
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS_GCS }}
      TF_VAR_google_credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      # GOOGLE_APPLICATION_CREDENTIALS: creds.json # 🆕 NEW: digunakan oleh GCS backend
      TF_VAR_project_id: sodium-pattern-465207-m9
      TF_VAR_region: us-central1
      TF_VAR_zone: us-central1-a

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ github.event.inputs.target_folder }} # 🔄 UPDATE

      - name: 💣 Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ${{ github.event.inputs.target_folder }} # 🔄 UPDATE
